name: 'Get LMS Version'
description: 'Retrieves the current active development version of Brightspace'
inputs:
  RALLY_API_KEY:
    description: 'Token to find active releases in Rally'
    required: true
outputs:
  LMS_VERSION:
    description: 'Current active development version of the LMS'
    value: ${{ steps.get-lms-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Get LMS Version
      id: get-lms-version
      run: |
        VERSION="20.24.4"
        if [ ${RALLY_API_KEY} != "" ]; then
          echo "RALLY_API_KEY detected, returning hard-coded release version..."
        else
          echo "RALLY_API_KEY is required, failing..."
          exit 1
        fi
        echo "$VERSION is the active development release."
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RALLY_API_KEY: ${{ inputs.RALLY_API_KEY }}
