name: Release
on:
  push:
    branches:
      - ekoopmans/npm-publish-tags

jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Match LMS Release
        uses: ./match-lms-release
        with:
          RALLY_API_KEY: ${{ secrets.RALLY_API_KEY }}
          GITHUB_TOKEN: foo
          NPM: true
          NPM_TOKEN: foo
          DRY_RUN: true
